import type { Metadata } from "next";
import { Host_Grotesk } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider"
import { ClerkProvider } from '@clerk/nextjs'
import ConvexClerkProvider from "@/components/convex-clerk-provider";
import { Toaster } from "sonner";

const outfit = Host_Grotesk({subsets:['latin'],variable:'--font-sans'});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", outfit.variable)}>
      <body
        className={` antialiased`}
      >
         <ClerkProvider>
      <ConvexClerkProvider>
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster/>
          </ThemeProvider>
      </ConvexClerkProvider>
       </ClerkProvider>
      </body>
    </html>
  );
}
